### ISSUE TITLE
Setting label to story

### ISSUE THREAD

**Issue by SPopenko** [jsmestad/pivotal-tracker#99]
Hi there! :)
Is it possible to set label to story using this gem?

**Comment by anuja-joshi** [comment]
@SPopenko  you can set label to story using `update` method

```
     @story.update(labels: 'some label')
```
  
ref: [here] (https://github.com/jsmestad/pivotal-tracker/blob/master/lib/pivotal-tracker/story.rb#L66)

**Comment by SPopenko** [comment]
Thanks @anuja-joshi
